"""Query Transformation Module using Ollama (MedGemma).

Generates multiple diverse search queries from a single user question
to expand semantic retrieval coverage (multi-query perspective expansion).
"""

import re
import time
import logging
from typing import List, Dict, Any
import ollama

from src.config import OLLAMA_MODEL, OLLAMA_NUM_CTX, QUERY_GEN_TEMPERATURE

logger = logging.getLogger(__name__)


class MultiQueryGenerator:
    """Generates alternative and sub-aspect search queries using an LLM."""

    def __init__(self, model_name: str = OLLAMA_MODEL):
        self.model_name = model_name

    def generate_queries(
        self,
        user_query: str,
        num_queries: int = 4,
        include_original: bool = True
    ) -> Dict[str, Any]:
        """Generate alternative search queries for a given user question.

        Args:
            user_query: The original question from the user.
            num_queries: Total number of queries to generate (excluding or including original).
            include_original: Whether to ensure the original query is retained in the list.

        Returns:
            Dict containing:
                - 'queries': List of clean search query strings.
                - 'raw_output': Raw text generated by the model.
                - 'elapsed_sec': Time taken in seconds.
                - 'model': Model used.
        """
        prompt = (
            f"You are an AI search query specialist for a scientific literature retrieval system.\n"
            f"The user is asking: \"{user_query}\"\n\n"
            f"Generate {num_queries} distinct and specific search queries to retrieve relevant scientific literature.\n"
            f"Guidelines:\n"
            f"- Generate queries that capture different perspectives, technical sub-aspects, and synonyms.\n"
            f"- Do NOT answer the question.\n"
            f"- Output ONLY a numbered list of queries (e.g. 1. query one, 2. query two).\n"
            f"- Do not include introductory or concluding remarks."
        )

        start_time = time.time()
        try:
            response = ollama.chat(
                model=self.model_name,
                messages=[{"role": "user", "content": prompt}],
                options={
                    "num_ctx": OLLAMA_NUM_CTX,
                    "temperature": QUERY_GEN_TEMPERATURE
                }
            )
            raw_text = response["message"]["content"]
        except Exception as e:
            logger.warning(f"Ollama call failed ({e}), falling back to heuristic query variations.")
            raw_text = ""

        elapsed_sec = time.time() - start_time
        parsed_queries = self._parse_queries(raw_text, user_query, num_queries)

        if include_original and user_query not in parsed_queries:
            # Prepend original query as the primary query
            queries = [user_query] + [q for q in parsed_queries if q.lower() != user_query.lower()]
            queries = queries[:num_queries]
        else:
            queries = parsed_queries[:num_queries]

        return {
            "queries": queries,
            "raw_output": raw_text,
            "elapsed_sec": round(elapsed_sec, 3),
            "model": self.model_name
        }

    def _parse_queries(self, text: str, original_query: str, expected_count: int) -> List[str]:
        """Clean and parse LLM response into a list of queries."""
        if not text:
            return self._heuristic_fallback(original_query, expected_count)

        # Remove thinking / reasoning blocks (e.g., <thought>...</thought> or leading thought)
        cleaned = re.sub(r"<thought>.*?</thought>", "", text, flags=re.DOTALL)
        if "thought\n" in cleaned.lower()[:20]:
            # Some local GGUF models output 'thought\n...' before the answer
            # Find where numbering starts
            match = re.search(r"(?:^|\n)\s*1[\.\)]\s*", cleaned)
            if match:
                cleaned = cleaned[match.start():]

        queries = []
        for line in cleaned.strip().split("\n"):
            line = line.strip()
            if not line:
                continue
            # Match lines like "1. query", "1) query", "- query", "* query"
            m = re.match(r"^(?:\d+[\.\)]|[-*•])\s*(.+)$", line)
            candidate_line = m.group(1).strip() if m else line

            # Check if query contains explicit quotes, e.g. "Transformer model advantages"
            quote_match = re.search(r'["\']([^"\']{4,100})["\']', candidate_line)
            if quote_match:
                query_text = quote_match.group(1).strip()
            else:
                # Strip markdown bold prefix like "**Aspect 1:**"
                query_text = re.sub(r"^\*\*[^*]+\*\*[:\-]?\s*", "", candidate_line)
                # Strip trailing explanation if separated by dash
                query_text = re.split(r"\s+[-–—]\s+", query_text)[0].strip()

            query_text = query_text.strip("\"'`*")
            if query_text and len(query_text) > 3 and not query_text.lower().startswith(("here are", "sure", "these queries", "the following")):
                queries.append(query_text)

        # Deduplicate while preserving order
        unique_queries = []
        seen = set()
        for q in queries:
            norm = q.lower()
            if norm not in seen:
                seen.add(norm)
                unique_queries.append(q)

        # Fallback if parsing didn't find enough queries
        if len(unique_queries) < 2:
            return self._heuristic_fallback(original_query, expected_count)

        return unique_queries

    def _heuristic_fallback(self, original: str, count: int) -> List[str]:
        """Heuristic rule-based query variations when LLM is unavailable."""
        variations = [original]
        words = original.rstrip("?.!").split()

        # Aspect 1: technical keywords
        variations.append(" ".join(words) + " mechanisms and clinical effects")
        # Aspect 2: overview / review
        variations.append(" ".join(words) + " systematic review analysis")
        # Aspect 3: comparative / impact
        variations.append("impact and outcomes of " + " ".join(words))

        return variations[:count]
